version: '3.8'
services:
  react:
    build: ./frontend
    container_name: sf-react
    depends_on:
      - express
      - mysqldb
    ports:
      - 3000:3000
    restart: on-failure 

    links:
      - mysqldb

 

  express:
    build: ./backend
    container_name: sf-express
    depends_on:
      - mysqldb
    ports:
      - 4000:4000

    restart: on-failure

  mysqldb:
    build: ./mysql 
    container_name: sf-mysql
    ports:
      - 3306:3306

    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: database
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    restart: on-failure 

    volumes:
      - ./db:/var/lib/mysql


volumes:
  db:
