version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: sf-mariadb
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./mysql:/var/lib/mysql


 
  express:
    build: ./backend
    container_name: sf-express
    depends_on:
      - mariadb
    ports:
      - 4000:4000

    environment:
        MYSQL_HOST_IP: mariadb


    
  react:
    build: ./frontend
    container_name: sf-react
    depends_on:
      - express
      - mariadb
    ports:
      - 3000:3000


    environment:
        EXPRESS_HOST_IP: express




volumes:
  mariadb-data:
    driver: local


