version: "3"
services:
  exchange-ms:
    image: exchange-ms
    ports:
      - "9000:9000"
  users-ms:
    image: users-ms
    ports:
      - "9001:9001"
  api-ms:
    image: api-ms
    ports:
      - "80:80"
