version: '2'
services:
  db:
    image: mariadb:10.7.4
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PORT: ${MYSQL_ROOT_PORT}
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3000:3000"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${MYSQL_ROOT_HOST}
      PMA_PORT: ${MYSQL_ROOT_PORT}
      PMA_USER:  ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_DATABASE: ${MYSQL_DATABASE}
      PMA_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ROOT_HOST: ${MYSQL_ROOT_HOST}
      PMA_ROOT_PORT: ${MYSQL_ROOT_PORT}
    depends_on:
      - db
    volumes:
      - ./db:/var/lib/mysql

  web:
    build: ./frontend
    ports:
      - "8080:8080"