
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: crypto_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/cryptodb
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

  db:
    image: postgres:13
    container_name: crypto_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cryptodb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
